Recall the Euclidean algorithm run on $a/b$ gives sequence of quotients $q_1,..., q_m$ $a/b = q_1 + (1 / <>)$ which we denote $C([q_1, ..., q_m])$ and let $C_0$ denote this truncated after $j$ quotients, as $j$ increases, $C_j$ becames closer to $a/b$. So, we can easily compute all convergents to $a/b$, 

The Rabin Cryptosystem is a cryptosystem similar to RSA but is secure under the assumption $n$ cannot be factored. Suppose $p, q$ are primes $eq.triple 3 mod 4$, let $p q = n$ and $PP = ellipse = ZZ^*_n$. Take $ KK = {(n, p, q): p, q = 3 (mod 4)} $ and define $e_k(x) = x^2 mod n$ $d_k(y) = sqrt(y) mod n$ $n$ is the public key and $(p,q)$ is the private key. Although Rabin is easier to describe than RSA, it has a drawback that there will be four square roots of $y mod n$. So, Bob cannot uniquely compute the plaintext from $y$, unless it has some form of redundancy. How can Bob decrypt $y$? By CRT, finding $x^2 eq.triple y (mod n)$ is equiv. to solving $z^2 eq.triple y (mod p)$ for $Z$. $ Z^2 eq.triple (mod q) $

If $Z$ is fixed, ${plus.minus sqrt(y) eq.triple Z (mod q)}, plus.minus sqrt(y) eq.triple Z (mod p)}$ and all choices of $plus.minus$ give all square roots of $y$. How to solve $Z^2 eq.triple y (mod p)$ ? When $p eq.triple 3 (mod 4)$ there is a simple formula for $Z$. Note Euler's criterion says that $y^(p-1) eq.triple 1 (mod p)$, Since by construction $y$ is a $Q R mod p$. Multiply both sides by $y$: $ y^((p+1)/2) eq.triple y (mod p) $ and since $(p+1)/2$ is even, $(y^((p+1)/4))^2 eq.triple y (mod p)$, so $y((p+1)/4) mod p$ is a square root of $y mod p$. Similarly, $y((q+1)/4)$ is a square root of $y mod q$. If $p eq.triple 1 (mod 4)$ there is no deterministic square root algorithm known, but a playtime Las Vegas algorithm is known.

We'll show Rabin is secure if $n$ is hard to factor, i.e, if Rabin can be broken (i.e, square roots can be computed) then $n$ can be factored. So we show that factoring $n$ reduces square roots $mod n$ or $ "Factor"(n) <= sqrt("in" ZZ_n^*)$. So suppose an oracle exists for computing square roots $mod n$. We'll give a Las Vegas algorithm to factor $n$ with failure probability of at most $1/2$: 

Choose a random $r in ZZ_n^*$ $ y := r^2 mod n $ $ x := sqrt(y mod n) $ if $x eq.triple plus.minus r (mod n)$ then return failure else return $gcd(x+r, n)$ (a nontrivial factor.
Note $n^2 eq.triple r^2 (mod n)$, but $x eq.triple plus.minus r (mod n)$ so $n | (x - r)(x + r)$ but $n !| x-r$ and $n !| x+r$. Since $n = p,q$, $p, q "prime"$ $p q | (x-r)(x+r)$ implies $p q | (x-r)$ or $p q| (x+r)$ or $(p | (x-r) & q | (x+r))$ or vice versa. The first $z$ cases contradicts $n !| (x plus.minus r)$, so we have $p | (x-r)$ and $q !| (x-r)$ or vice versa. Thus, $gcd(x-r, n)$ would be $p$ and $q$. What's the success probability? Let $w$ be a non trivial square root of $1$. Then ${plus.minus r, plus.minus w r}$ are the $4$ roots of $r^2$. The oracle doesn't know the value of $r$, which was chosen randomly, and so it doesn't know which of the roots will lead to success. Half the roots it return will lead to success (when it return $plus.minus w r$), so with probability $1/2$ the return value return value leads to a non trivial $gcd$. This also shows Rabin is insecure against  a chosen cipher-text and plain-text, $w$ this algorithm would let them fator $n$, as the chosen cipher-text attack assumes a square root oracle exists.

Semantic Security: So far we've assumed Eve wants to break a cryptosystem by finding the secret/private key (called a total break). A partial break is when Eve can decrypt a previously unseen cipher-text (without the key) or learn some information about the plain-text given the cipher-text. Or, Eve might be able to distinguish between the encryption of $Z$ are different plain-text ot between a cipher-text and random string. The distinguishbility problem is, give $x_1, x_2, y$ with $e_K(x_i) = y$ for $i = 1 "or"i = 2$ to determine if $i = 1 or i = 2$ If encryption is done using a public key encryption, then randomness, must be introduced in order to make this a difficult problem. If the problem  cannot be solved with probability more than $1/2$ the cryptosystem is said to be semantically secure. Achieveing this is difficult, since it is a weak advesarial goal, and any bit of info leaked about the plain-text may make the distinguishability problem solvable. For example, RSA has the following partial break: Since $b$ is coprime to $nothing(n) = (p-1)(q-1)$ which is even, $b$ is odd. Then the Jacobi symbol $(y/n) = (x^b/n) = (x/n)^b = (x/n)$ since $plus.minus 1$ raised to an odd number, doesn't change. So, Eve can compute $(x/n)$ 

It is possible to show that RSA doesn't leak other information (assuming it is secure) like the value of $(x mod Z)$. To do this, you reduce the problem of decrypting RSA to the problem of computing $x mod Z$ from y, showing RSAdecryption($y$) $<="parity"(y)$ where $"parity"(y) = d_k(y) mod Z$. It can be shown that if the distinguishability problem connot be solved then no information of any king is leaked about the plain-text, because any such into would allow solving the distinguishability problem. Since RSA is deterministic, Eve can solve this problem by simply computing $e_1(x), e_2(x)$, and checking which is $ = y$. We introduce randomness to the cryptosystem with a random oracle $G: ZZ_2^K -> ZZ_2^m$ which in practice will be realized by a hash function.

