== Miller-Rabin primality test:
Write $n-1=2^k m$ for $k in ZZ$ and $m$ odd, then consider the sequence $a^(n-1)mod n, a^((n-1)/2) mod n, a^((n-1)/2^2) mod n,..., a^((a-1)/2^k)$, Recall if n is prime, the first entry will be 1 by Fermat's little theorm, and the second entry will be $plus.minus 1$ by Euler's criterion. In general if $n$ is prime, this sequence must be of the form. $(1, 1,... , 1, -1, *, *, *)$ or $(1, 1, ..., 1)$  where $*$ denotes a number not $plus.minus$. So, given $n$, if the above sequence is of the form $(*, *, ..., *)$ (quite likely if $n$ is no prime) or $(1, 1, 1, *, *, *, ..., *)$ then we can be sure that $n$ is not prime, Every number is the sequence is the square of the number to its right, so in this case we would have a number not $plus.minus 1$ when squared gives $1$ which cannot happen when $n$ is prime. The first case cannot happen when $n$ is prime by Fermat's little theorm. So, Miller-Rabin computes this sequence starting from the right entry $(a^(n-1)2^k) mod n = a^m mod n$. If is $plus.minus 1$, $n$ is likely prime. Then square it to compute the number to its left. If this is $-1$ $n$ is likely prime, but if it is $1$, $n$ cannot be prime as we found a square root of $1$ that is not $plus.minus 1$. Repeat this until the $2^"nd"$ last entry which must be $plus.minus 1$ by Euler's criterion if $n$ is prime. The error probability is at most $1/4$, and thos is very pessimistic in practice.

Square roots $mod n$: Say $n$ is odd and $a in ZZ^*_n$. We know if $n$ is prime that has either two square roots $mod n$ (when $(a/n) = 1)$ or no square roots $mod n$ when $(a/n) = -1)$. In fact, when $n$ is a prime power, i.e., $n = p^e$ for prime $p$ and $e in ZZ^*$, $a$ has two square roots exactly when $(a/p) = 1$. For general $n$, we have the following: 

$underline("Thm:")$ If $n > 1$ is odd and $n = attach(limits(pi), t: l, b: i = 1)p^(e_i)_i$ is its prime factorization then if $a in ZZ^*_n$ there are $2^l$ square roots of a when $(a/p_1) = (a/p_2) = dots.h = (a/p_l) = 1$ and no square roots if $(a/p_i) = -1$ for any $1 <= i <= l$

*Proof by CRT*:

$ y^2 eq.triple a (mod n) <=> cases(y^2 eq.triple a (mod p_1^e_1), y^2 eq.triple a (mod p_2^e_2), dots.v, y^2 eq.triple a (mod p_l^e_l)) $ when $(a/p_i) = -1$ for some, $i$, then $y^2 eq.triple (mod p_1^e_1)$ has no solutions, so $y_2 eq.triple (mod n)$ has more either.When $(a/p_i) = 1$ for all $i$, then each $y^2 eq.triple (mod p_i^e_i)$ has exactly two solutions, say $plus.minus b_i$. Each choice of $plus.minus$ results in a different system of congruences $ cases(y eq.triple +- b_1 (mod p_i^e_i), dots.v, y eq.triple +- b_l (mod p_i^e_i)) $ which is for each choice of $plus.minus$ gives a unique solution by CRT. Thus, as here are $2^l$ choices of $plus.minus$, there are $2^l$ solutions of $y^2 eq.triple a (mod n)$. A special case of this theorem says that for RSA moduli $n = p.q$ there are exactly $2^2 = 4$ square roots of $1 mod n$. Clearly $plus.minus$ are square roots of $1 mod n$ so, there are two non-trivial square roots of $1 mod n$. E.q., if $n = 403 = 13 * 31$m the roots of $1$ are $plus.minus 1$ and $plus.minus 92$ as $92^2 eq.triple 1 (mod 403)$. We'll show that knowledge of either non-trivial not of $1$ allows factoring $n$.

For suppose $y^2 eq.triple 1 (mod n)$, but $y !eq.triple plus.minus 1 (mod n)$ so $y$ is a non-trivial square root of $1 mod n$. This means that $n | (y^2 - 1)$ but $n !|(y plus.minus 1)$. This means $p q | (y^2 - 1) = (y - 1)(y + 1)$, so we know $p | (y-1)(y+1)$ which since $p$ is prime, $p | (y - 1)$ or $p | (y + 1)$. In the first case, we must have $q !| (y - 1)$, because if $q | (y - 1)$ and $p | (y - 1)$ then $p q | (y - 1)$ as $p,q$ are distinct prime, and this contadicts $n !| (y - 1)$. In the second case, we must have $q t !| (y + 1)$ as otherwise $p q | (y+1)$ but $n!|(y+1)$. Since $p$ is a common divisor of $y plus.minus 1$ and n, we can compute $gcd(n, y plus.minus 1) = p$ (in the first case, gcd(n, y - 1) = p and in the second case $gcd(n, y+1) = p$). E.g. in the example $ y = q_2 $ and $gcd(403, 92+1) = 31$ and $ gcd(403, 92 - 1) = 13$.
The besr general factoring algorithm. The number field sieve uses this kind of idea to factor $n$. The simplest factoring algorithm is trial division by all small primes up to some bound. Since any composite $n$ will have a prime factor $<= sqrt(n)$ you only need to trial divide $sqrt(n)$. However, if $n$ is $024$ bits then $n approx 2^512$, there are far too many divisors to check. Trial division is feasible upto $2^40$ or so, but become exponentially slower as $n$ increases. We'll cover some other attacks on RSA. First, note that it is cricial that $nothing(n)$ is publicaly revealed. For suppose $n = p q$ and $nothing(n) = nothing(p q) = nothing(p) nothing(q) = (p-1)(q-1)$. then substitute $q = n/p$ into this to get $nothing(n) = (p-1)(n/p - 1) = n - n/p - p + 1$ so, multiple by $p$ to get $p " " nothing(n) = n p - n p^2+p => p^2 + (nothing(n) - n - 1)p + n = 0$ which can be solved with the quadratic equation $ p = (n - nothing(n) + 1 +- sqrt(nothing(n) - n - 1)^2 - 4n)/2$. e.q, if $ n = 84773093$ and $nothing(n) = 84754668$ then $p = (18246 plus.minus sqrt(425104) / 2) = 9213 plus.minus 326 $, so $p$ is $9539 "or" 8887$.
