The output of the absorbing phase is $x_(K+1) xor x_k || y_(k+1) = f(0^r || y_k )$ and since $y_h = y_k$, this is $ = f(0^r || y_n) $ $ = x_(h+1) = y_(h+1) $ Thus, the output of the absorbing phase for both M and M' is the same, even though $m != m'$ , so $(m, m')$ is a collision. If $l$ is particularly small, we also have the option of a birthday attak in the hash function directly, which uses $approx sqrt(2^l)$ evaluations to find a collision. SHA-3 512 uses the sponge construction with $b=1600, r=576, c=1024$ so has collision security of 256 and preimage security of 512 bits. That is we expect $2^256$ ops to find a collision and $2^512$ ops to find a preimage of any hash. The SHA3 family supports "extendable output" for which the output length is controllable, e.g. in the hash function SHAKE256. 

== Message Authentication Codes (MACs)
MACs ensure integrity of a message - Alice sends a message to Bob and appends a tag, depending on a private key shared by Alice & Bob. If the message was corrupted, that would be detected, as the tag would no longer match. A common way of constructing, a MAC is to use an unkeyed hash function and incorporate a secret key as a part of the message to be hashed. However, this must be done carefully we'll sho whow to how to break some simple approaches of this.

Suppose we make a keyed hash function $h_k$ by taking an interated hash function $h$ and setting $"IV"=K$, keeping $k$ secret. Say $x$ has a length that is a a multiple of $t$ and $c: ZZ_2^(m+t) -> ZZ_2^m$ is the compression function to build h. We also assume K has m bits. We'll show if an adversary has a single message $x$ and a valid tag $t=h_k(x)$, they will be able to generate a valid tags for other messages. Let $x'$ be any bitstring of length $t$, and consider $m=x || x'$. Its tag is $h_k(x || x') = c(h_k(x) || x')$ so $h_k(m) = c(t || x')$, and Eve knows $c, t, x'$
Thus, $(m, t)$ is a valid pair that is a forgery of Eves done without knowing the key $k$. Even if $|x|$ is not divisible by $t$, a similar attack can be used. Say $y=x||"pad"(x)$ is the padding of $x$ in the preprocessing step. Here $|y| = r t$ for some integer $r$. Take $w$ any bitstring of length $t$, and define $x'=x||"pad"(x)||w$. The preprocessing step for this $x'$ would give $ y'=x'||"pad"(x') = x || "pad"(x) || w || "pad"(x') $ $ = y_1 y_2...y_r' "where" |y_i| = t "and" r' < r. $ Note $h_k(x) = z_r$ where $ z_r = c(z_(r-1) || y_r) $ $z_(r-1) = c(z_(r-2) || y_(r-1)) $ $ dots.v $ $ z_0 = "IV" = K $. Then Eve can compute $ z_(r+1) = c(h_k(x) || y_(r+1)) $ $ z_(r+2) = c(z_(r+1) || y_(r+2)) $ $ dots.v $ $ z_(r') = c(z_(r'-1) || y_r') = h_k(x') $ So, $(x', z_r') $ is a forgery from Eve, even through K is unknown and there is no assumption on the padding length. So, in general we want to avoid letting an advesary compute a message-tag pair $(x, y)$ for unknown key given prior valid pairs $ (x, y) $ ..., $ (x_Q, y_Q) $ using the same key. The pairs may be pairs observed by Eve, in which casse it is a know message attack or in a chosen message attack Eve has access to a "tag oracle" and can generate tags for messages $x_1, ..., x_Q$ that Eve chooses, Here $x!=x_1, ..., x_Q$ and $(x, y)$ is said to be a forgery. If the probability of a forgery is at least $epsilon$ the advsary is said to be a $(epsilon, Q)$-forges. (In known message attack, the attack should work woth probability $epsilon$ for regardless of the message seen). 
The attacks we just saw are therefore $(1, 1)$ - forgery attacks. Another obvios attack is to choose a key $k in KK$ at random and output $(x, h_k(x))$ for arbitary $x$. This would be a $(1/(|KK|), 0)$  - forgery attack. 

One standarized MAC is algorithm called HMAC constructs a MAC from a unkeyed hash function like SHA-1. The version we'll describe uses a 512 bit key k and 512-bit constants $"ipad" = 36 dots 36$ and $"opad" = 5C...5C$ (written in hex). If x is the message to be authenticated, the 160 bit MAC is computed as $ "HMAC"_k(x) = "SHA-1"((k xor "opad") || "SHA-1"((k xor "ipad") || x)) $ One can 

a fixed-size message and a collision-resistant hash function. It is also very efficient, as it uses only one call to SHA-1 on a long message (the "outer") SHA-1 takes constant time as it is on messages of length 512 + 160.
