The idea of public key cryptography was proposed by Diffie-Hellmann in 1976, and in 1977 the RSA cryptosystem was proposed and is still in use today. Bob's encryption function $e_k$ should be efficient to compute, but the inverse $e_k^-1$ should only be effiecient to compute Bob, who has some secret information that enables him to compute it effficiently. In RSA, encryption is done via $f: ZZ_n -> ZZ_n$ of the form $x -> x^b "mod"n$ where $n = p.q$ for primes $p, q$. Computing $f^(-1)$ is difficult if you just know $n$, but if you also know $p,q$ then the inverse can be computed efficiently. First we'll review some number theory background. The Euclidean Algorithm finds the greatest common divisor (gcd) of two numbers, and the extended euclidean algorithm (EEA), which will allow us to compute the inverse of a number $a^(-1) "mod"n$. Recall that $a^(-1) in ZZ_n$ is defined so $a.a^(-1) eq.triple 1 "mod" n$, and it exists when $gcd(a, n) eq 1$. $ZZ_n$ is the number $"mod"n$ $ZZ_n^*$ is the numbers mod $n$ with an inverse.
$ ZZ_a^* = {a in ZZ_n : "gcd"(a, n) = 1}; $ its size $|ZZ_n^* eq phi(n)$ where $phi$ is the Euler's phi function. 

- Euclidean Algorithm
Input $a, b in ZZ^*$
Set $ r_0 := a, r_1 := b, $ and write $ r_0 = q_1r_1 + r_2 $ where, $ 0<= r_2 <= r_1 $ (and repeat) $ r_1 = q_2r_2 + r_3 $ $ dots.v $ $ r_(m-2) = q_(m-1)r_(m-1) + r_m $ $ r_(m-1) = q_m r_m $. Output $r_m$ 

Note $gcd(a, b) = gcd(r_0, r_1)$
$ = gcd(r_0-q_1r_1, r_1) $
$ = gcd(r_2, r_1) $
$ = gcd(r_1, r_2) $
$ = gcd(r_1-q_2r_2, r_2) $
$ = gcd(r_3, r_2) $
$ dots.v $
$ = gcd(r_(m-1), r_m) $
$ = gcd(r_m, 0) = r_m $

We can now tell if $ a^(-1) "mod" n $ exists, by computing gcd($a, n$), but how to find $a^-1$? We run the same computation but store some extra information, storing the $r_i, s $ as a weighted sum of $a "and" b$. Note it is easy to write $r_0, r_1$ as a sum of $a$ and $b$: $ r_0 = 1.a + 0.b = s_0.a + t_0.b $ $ r_1 0.a + 1.b = s_1.a + t_1.b $ to form $r_2$, subtract $q_1.r_1$ from $r_0$ : $ r_2 = r_0 - q_1r_1 = 1.a + (-q_1)b = s_2.a + t_2.b $ Proceeding in this way subtracting $q_j + r_(j-1)$ from $r(j-2)$, we find $r_j = s_j a + t_j .b$ where $s_j "and" t_j$ are integers found via $ t_j = t_(j-2) - q_(j - 1) t(j-1) $ $ S_j = S_(j-2) - q(j-2) t(j - 2) $ with $ (S_0, t_0) = (1, 0) $ $ S_1, t_1 = (0, 1) $ Then EEA($a, b$) returns $(r_m, s_m, t_m)$. Why is this useful? To compute $a^(-1) "mod"n$ run EEA($a, n$) which gives $s, t$ with $ 1 = s.a + t.n eq.triple s.a "mod"(n) $ So $ a^-1"mod"(n) = s$. The Chinese Remainder Theorm (CRT) is a method of solving systems of congruences of the form $ x eq.triple a_i ("mod" m_1) $ $ x eq.triple a_2 ("mod" m_2) $ $ dots.v $ $ x eq.triple a_r ("mod" m_r) $ where all $M_i s$ are pairwise coprime. The CRT says this has a unique solution mod $M = m_1x dots x m_r$
and CRT gives a formula for $x$. Consider the "projection" $chi : ZZ_m -> ZZ_m_1 x dots ZZ_m_r $ $ chi (x) = (x "mod" m_1, ..., x "mod" m_r) $ CRT essentially says $ chi $ is a bijection and formula for $chi^(-1)$. For $1 <= i <= r$ define $M_i = M/m_i = pi_(j=1)(j!=i)^r M_j in ZZ $ Also note gcd($M_i, m_i)$ = 1 since gcd($m_j, m_i$) = 1 for all $j != i$. Thus, we can define $y_i = M_i^-1 "mod" m_i $ and find $y_i$ with EEA($m_i, M_i$). Now define $rho : ZZ_m_1 X ... X ZZ_m_r -> ZZ_m $ by $ (a_i, ... a_r) |-> sum_(i= 1)^r a_i M_i y_i "mod" M $. The system if congruences is equivalent to solving $ chi (x) = (a_i, ..., a_r) $, and the system has the general solution $ x = rho (a_1, ..., a_r)$. First, we'll show $ X = rho (a_i, ..., a_r) $ is a solution of all congruences $ x eq.triple a_i ( "mod" M_i)$. For concrateness, we'll just show $ X eq.triple a_1 ("mod" M_1) $ but the argument is the same for all $M_i$. Note $ X = (a_i M_i y_i + sum_(i=2)^r a_i M_i y_i) "mod" M$. Note $m_1 | M_i$ for all $ 2<=i<=r $ (here the | means divides), so $M_i eq.triple 0 ("mod" m_1)$ and $sum_(i=2)^r a_i M_i y_i eq.triple 0 ("mod" m_1$. Also $y_1 = M_1^(-1) "mod" m_1$, so $M_1 y_1 <= 1 ("mod" m_1)$, and so $X eq.triple a_1 ("mod" m_1)$. Now we just need to show that $X$ is the only solution of $chi (x) = (a_i, ..., a_r) $. We just showed this map $chi$ is surjective (onto) since $chi$ maps $X$ to $(a_i, ..., a_r)$ for any value of $a_i s$. But the domain $ZZ_m$ and codomain $ZZ_m_1 X... X ZZ_m_r$ are the same size, so $chi$ must also be injective and hence a bijection, with $chi (rho(a_1, ..., a_r)) = (a_1,...a_r)$, i.e, $rho = chi^-1$. For RSA, we'll work in $ZZ_n$ where $ n = p.q $ for prime $p, q$. Since gcd($p, q$) = , CRT says $ZZ_n$ is isomorphic to $ZZ_p X ZZ_q$.
